### ISSUE TITLE
Improve the Project Plan using the feedback

### ISSUE THREAD

**Issue by simitii** [bounswe/bounswe2019group3#34]
Below, you can find the feedbacks for your project plan. Similar to the previous feedbacks, you should keep in mind that the provided feedback is not limited to these, they may be samples about common mistakes, so that you can apply to the other ones if fits.

- [x] In your project plan, you should also specify the end date.

- [x] From your project plan, I cannot see the whole resource names (it doesn't fit the window).

- [x] From the spreadsheet of your project plan, I cannot see the predecessors. By looking to your gantt chart, I understand that you define some predecessors. However, it is very hard to follow from the gantt chart, so I cannot give any feedback regarding the predecessors. Please show predecessors also in the spreadsheet of your project plan.

- [x] Be careful about the Turkish characters for resource names. If you cannot provide Turkish characters, then use the English versions.

- [x] Project plan is an important tool to plan the future. However, in your case, you define the things you have done until present moment. I understand that you don't know the details of your future tasks, but you should update your project plan with the upcoming assignments even though there is no assignment for updating the project plan (e.g., I can't see your plans for assignment 7).
